sentence = noun.phrase " " verb.phrase
opt.noun.phrase = noun.phrase | ""
noun.phrase = adjective.phrase " " noun.phrase | noun
verb.phrase = opt.adverb.phrase " " verb " " opt.adverb.phrase | opt.adverb.phrase " " verb " " noun.phrase
adjective.phrase = adjective
opt.adverb.phrase = adverb.phrase | ""
adverb.phrase = adverb
noun = "ideas"
verb = "hug"
adjective = "colorless" | "green"
adverb = "furiously"