sentence = noun.phrase " " verb.phrase

; Noun stuff
noun.phrase = adjective.phrase " " noun | noun
noun = "ideas"

; Adjective stuff
adjective.phrase = adjective ", " adjective.phrase | adjective
adjective = "colorless" | "green"

; Verb stuff
verb.phrase = verb " " adverb | adverb " " verb " " noun.phrase
; hug instead of sleep to add transitivity
verb = "hug"

; Adverb stuff
adverb.phrase = adverb ", " adverb.phrase | adverb
adverb = "furiously"