; ; This generates USPS postal addresses

; start symbol
postal.address = name.part street.address zip.part

; lines
name.part = personal.part last.name opt.suffix.part "\n" | personal.part name.part
personal.part = first.name | initial "."
street.address = house.num street.name opt.apt.num "\n"

; necessary sections
zip.part = town.name "," state.code zip.code "\n"

; optionals
opt.suffix.part = "Sr." | "Jr." | roman.numeral | ""
opt.apt.num = "Apt" apt.num | ""